use_frameworks!

platform :ios, '9.0'

target 'VandMarvelCharacters_Example' do
  pod 'VandMarvelCharacters', :path => '../'

  target 'VandMarvelCharacters_Tests' do
    inherit! :search_paths

    
  end
end
