use_frameworks!

platform :ios, '11.0'

inhibit_all_warnings!

target 'VandMarvelCharacters_Example' do
  pod 'VandMarvelCharacters', :path => '../', :inhibit_warnings => false

  pod 'SwiftLint'
  pod 'SnapKit', '~> 5.0.0'

  pod 'VandMarvelUIKit', :git => 'git@github.com:Vandcarlos/VandMarvelUIKit.git', :branch => 'main'
  pod 'VandMarvelAPI', :git => 'git@github.com:Vandcarlos/VandMarvelAPI.git', :branch => 'main'

  target 'VandMarvelCharacters_Tests' do
    inherit! :search_paths

    pod 'Fakery'

  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      end
    end
  end
end
